wa_blog:
    resource: "@WABlogBundle/Resources/config/routing.yml"
    prefix:   /blog

wa_flickr:
    resource: "@WAFlickrBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
